### PR TITLE
Ensure muting in the editor removes audio from the export

### LINKED ISSUE #525: Audio included even when disabled in the Editor
**macOS version:**    10.13.6
**Kap version:**      3.0.0-beta.1

#### Steps to reproduce
* Enable Audio Recording in Preferences
* Create a Kapture
* Select a format that supports audio
* Mute the audio in the Editor
* Export 

#### Current behavior
* Audio is still included in the export 

#### Expected behavior
* Audio should not be included in the export

#### Workaround
* Completely disable the Audio Recording setting

### PR DESCRIPTION
**Pull request by karaggeorge**
Fixes #525

### CODE REVIEW

File: renderer/containers/editor.js [hunk 1]
```diff
@@ -158,7 +158,7 @@ export default class EditorContainer extends Container {
         fps,
         startTime,
         endTime,
-        muted
+        muted: isMuted
```
Comment (sindresorhus) [inline renderer/containers/editor.js]: I think `muted` should be renamed to `isMuted`, both here and on the main process side. Better to be consistent.

Comment (karaggeorge) [reply renderer/containers/editor.js]: eeae224
