### PR TITLE
Fix fullscreen coordinates

### LINKED ISSUE #310: Resolve feedback in #306
It was merged to unblock @sallar, but there were some unresolved things that need to be fixed: https://github.com/wulkano/kap/pull/306#issuecomment-355160210

### PR DESCRIPTION
**Pull request by sallar**
Fixes #310 

Output:

fullscreen

### CODE REVIEW

File: app/src/renderer/js/main.js [hunk 1]
```diff
@@ -100,6 +100,12 @@ document.addEventListener('DOMContentLoaded', () => {
     cropperBounds.width -= 2;
     cropperBounds.height -= 2;
 
+    // If we're recording fullscreen, set x, y to zero
+    if (dimensions.app && dimensions.app.isFullscreen) {
+      cropperBounds.x = 0;
+      cropperBounds.y = 0;
```
Comment (sindresorhus) [inline app/src/renderer/js/main.js]: The cropper buffer is on all sides, not just the bottom-left. So you need to adjust width and height too. Add 2 px.

Comment (sallar) [reply app/src/renderer/js/main.js]: @sindresorhus that's already done. I tested it the width and height are correct

Comment (sallar) [reply app/src/renderer/js/main.js]: ^ the above screen capture shows it
