### PR TITLE
Work around the "Save" dialog bug in Electron

### LINKED ISSUE #368: File browser prompt expand/collapse not working
**Platform:** MacOS 10.13.3
**Kap Version:** 2.0.0 (2.0.0.681)

### Steps to reproduce
When saving an exported format, the file browser only shows the collapsed version. Attempts to expand to view file list do not produce the file list.
1. After capturing the screen, view the playback
2. select Export GIF from controls on the bottom right of the screen
3. this will reveal the file browser prompt

### Current behaviour
click expor gif shows the file system prompt:
screen shot 2018-02-01 at 2 02 09 pm

after clicking arrow down to expand (at the end of Save As line)
screen shot 2018-02-01 at 2 03 10 pm

**the screen does not expand to show the contents of the folder.**

### Expected behaviour
After clicking arrow down to expand (at the end of Save As line), screen expands to show file system (as this other example):
screen shot 2018-02-01 at 2 05 01 pm

### Workaround
Did not encounter a method to expand the screen.

### PR DESCRIPTION
**Pull request by karaggeorge**
(Hopefully) Fixes #368 

Tested locally on all 3 places we use a save dialog, and it's working fine

Used the workaround mentioned here: https://github.com/wulkano/kap/issues/368#issuecomment-473526414

`promisify` epxects an error-first callback, while electron's `showSaveDialog` calls it just with the file path or `undefined` if the user cancels. I used a catch block to get the file path, not sure if there's a better way, or if I should just write a small utility to implement `promisify` for this specific use-case

### CODE REVIEW

**Comment by sindresorhus** [comment]
Use https://github.com/sindresorhus/pify with the `{errorFirst: false}` option.

**Comment by karaggeorge** [comment]
@sindresorhus I knew there was something out there, but I couldn't find it. Updated 👍

File: main/editor.js [hunk 1]
```diff
@@ -94,7 +94,17 @@ const setOptions = options => {
...
-ipc.answerRenderer('save-original', ({inputPath, outputPath}) => promisify(fs.copyFile)(inputPath, outputPath, fs.constants.COPYFILE_FICLONE));
+ipc.answerRenderer('save-original', async ({inputPath}) => {
+  const now = moment();
+
+  const path = await pify(dialog.showSaveDialog, {errorFirst: false})(BrowserWindow.getFocusedWindow(), {
+    defaultPath: `Kapture ${now.format('YYYY-MM-DD')} at ${now.format('H.mm.ss')}.mp4`
+  });
+
+  if (path) {
+    return pify(fs.copyFile)(inputPath, path, fs.constants.COPYFILE_FICLONE);
```
Comment (sindresorhus) [inline main/editor.js]: Better to await than return for readability reasons.

File: main/editor.js [hunk 2]
```diff
@@ -94,7 +94,17 @@ const setOptions = options => {
 
 const getEditors = () => editors.values();
 
-ipc.answerRenderer('save-original', ({inputPath, outputPath}) => promisify(fs.copyFile)(inputPath, outputPath, fs.constants.COPYFILE_FICLONE));
+ipc.answerRenderer('save-original', async ({inputPath}) => {
+  const now = moment();
+
+  const path = await pify(dialog.showSaveDialog, {errorFirst: false})(BrowserWindow.getFocusedWindow(), {
```
Comment (sindresorhus) [inline main/editor.js]: Would be more readable to promisify it at the top-level (top of the file):

```js
const showSaveDialog = pify(dialog.showSaveDialog, {errorFirst: false});
```

**Comment by sindresorhus** [comment]
Works great 👌
