### PR TITLE
Save the last used directory

### LINKED ISSUE #659: Export should remember last location
**macOS version:**    18.5.0 (darwin)
**Kap version:**      3.0.0-beta.5

#### Steps to reproduce
Record a video, choose Gif as export target, hit export, it is always in the Kaptures folder.

#### Current behavior
No matter where I saved previously, it starts in the Kaptures folder.

#### Expected behavior
It remembers the previous save location.

#### Workaround
I use this to add gifs to PR's many times a day, and dragging from my desktop is just the easiest way for me to do that outside of always having a finder opened to the kaptures directory, which I don't. As it stands now, I have to remember to change the directory, or forget and hunt around to find that directory. It would be great to offer an option to not always preset to it but instead the last used directory.

### PR DESCRIPTION
**Pull request by karaggeorge**
Fixes #659

### CODE REVIEW

File: main/export-list.js [hunk 1]
```diff
@@ -22,6 +23,7 @@ const Export = require('./export');
 
 const ffmpegPath = util.fixPathForAsarUnpack(ffmpeg.path);
 const showSaveDialog = pify(dialog.showSaveDialog, {errorFirst: false});
+let lastSavedDir = null;
```
Comment (sindresorhus) [inline main/export-list.js]:
```suggestion
let lastSavedDirectory;
```

File: main/export-list.js [hunk 2]
```diff
@@ -22,6 +23,7 @@ const Export = require('./export');
 
 const ffmpegPath = util.fixPathForAsarUnpack(ffmpeg.path);
 const showSaveDialog = pify(dialog.showSaveDialog, {errorFirst: false});
+let lastSavedDirectory = null;
```
Comment (sindresorhus) [inline main/export-list.js]: There's no reason to initialize with `null`.
```suggestion
let lastSavedDirectory;
```
