### PR TITLE
Notarize app during packaging

### LINKED ISSUE #754: Unable to launch on Catalina
**macOS version:** 10.15.1
**Kap version:** 3.0.0

#### Steps to reproduce
Downloaded Kap from https://getkap.co/ and then tried to launch after installing macOS Catalina

#### Current behavior
When trying to launch I get a popup saying it needs to be updated by the developer:
Screen Shot 2019-11-20 at 11 15 24 AM

#### Expected behavior
It would let me open it and try it out :)

### PR DESCRIPTION
**Pull request by karaggeorge**
Fixes #754 

Tried following this guide: https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db

Need `APPLE_ID` and `APPLE_ID_PASSWORD` set in CI

### CODE REVIEW

**Comment by skllcrn** [comment]
I've added the required env vars to CI @karaggeorge

**Comment by karaggeorge** [comment]
@sindresorhus Got [this error](https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma123/v4/08/ed/55/08ed55dd-d39b-145b-34e9-8b75bdb20e58/developer_log.json?accessKey=1574540507_9177391453601885790_r6PPZI4dyuSotItNQppyYg1ZN5tdDepvXYLLzkQZvlNssCyynJa4Rob0MaN1vNnftGIaPYSngJReZmlVKDv39wMqGcEJm9rPb2Mf3LcZ%2Ft1yMHWZH11hNyT1JE3YJIabIiyJw%2BdflJ%2BzSx8HJ%2F4iGsuYrVb%2FLDDbLfeRfyNh9oM%3D)

Basically it wants every executable (even in node_modules) to be signed

File: after-sign-hook.js [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+module.exports = async function (params) {
+  // Only notarize the app on Mac OS only.
+  if (process.platform !== 'darwin') {
+    return;
+  }
+
+  console.log('afterSign hook triggered', params);
+
+  // Same appId in electron-builder.
+  const appId = 'com.wulkano.kap';
```
Comment (sindresorhus) [inline after-sign-hook.js]: Just fetch it from package.json

File: after-sign-hook.js [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+  try {
+    await electronNotarize.notarize({
+      appBundleId: appId,
+      appPath,
+      appleId: process.env.APPLE_ID,
+      appleIdPassword: process.env.APPLE_ID_PASSWORD
+    });
+  } catch (error) {
+    console.error(error);
```
Comment (sindresorhus) [inline after-sign-hook.js]:
```suggestion
    console.error(error);
    return;
```

File: after-sign-hook.js [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+
+  console.log('afterSign hook triggered', params);
+
+  // Same appId in electron-builder.
+  const appId = 'com.wulkano.kap';
+
+  const appPath = path.join(params.appOutDir, `${params.packager.appInfo.productFilename}.app`);
+  if (!fs.existsSync(appPath)) {
+    throw new Error(`Cannot find app at: ${appPath}`);
+  }
```
Comment (sindresorhus) [inline after-sign-hook.js]: I don't see the point of this.`electronNotarize` already throws if it can't find the app. Just remove the below try/catch instead.

File: after-sign-hook.js [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+const fs = require('fs');
+const path = require('path');
+const electronNotarize = require('electron-notarize');
+
+module.exports = async function (params) {
+  if (process.platform !== 'darwin') {
+    return;
+  }
+
+  console.log('afterSign hook triggered', params);
```
Comment (sindresorhus) [inline after-sign-hook.js]: I would remove this. Not very useful.

File: after-sign-hook.js [hunk 5]
```diff
@@ -0,0 +1,37 @@
+// See: https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db
+
+'use strict';
+const fs = require('fs');
+const path = require('path');
+const electronNotarize = require('electron-notarize');
+
+module.exports = async function (params) {
```
Comment (sindresorhus) [inline after-sign-hook.js]:
```suggestion
module.exports = async params => {
```

File: after-sign-hook.js [hunk 6]
```diff
@@ -0,0 +1,37 @@
+// See: https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db
```
Comment (sindresorhus) [inline after-sign-hook.js]: I would call this file `notarize.js`. That's what it does.

**Comment by karaggeorge** [comment]
@sindresorhus Made the updates 👍 

I noticed this in the build logs: 

```
  • Current build is a part of pull request, code signing will be skipped.
Set env CSC_FOR_PULL_REQUEST to true to force code signing.
There are serious security concerns with CSC_FOR_PULL_REQUEST=true (see the  CircleCI documentation (https://circleci.com/docs/1.0/fork-pr-builds/) for details)
If you have SSH keys, sensitive env vars or AWS credentials stored in your project settings and untrusted forks can make pull requests against your repo, then this option isn't for you.
```

Might be the reason the notarizing fails in the PR build

Note:

I added the only run on master check, since it might take up to 15 minutes and we don't need that for PR builds. Disabled for now, until we can make it work.

File: notarize.js [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+  if (process.platform !== 'darwin') {
+    return;
+  }
+
+  // Only notarize the app on the master branch
+  // if (process.env.CIRCLE_BRANCH !== 'master') {
+  //   return;
+  // }
+
+  const packageJson = JSON.parse(fs.readFileSync('./package.json'));
```
Comment (sindresorhus) [inline notarize.js]: Why not just:

```suggestion
  const packageJson = require('./package.json');
```

File: notarize.js [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+  const {appId} = packageJson.build;
+
+  const appPath = path.join(params.appOutDir, `${params.packager.appInfo.productFilename}.app`);
+
+  console.log(`Notarizing ${appId} found at ${appPath}`);
+
+  try {
```
Comment (sindresorhus) [inline notarize.js]: Remove try/catch.

File: notarize.js (hunk 7 above)
Comment (karaggeorge) [reply notarize.js]: 🤦‍♂ forgot you can just require json files

**Comment by karaggeorge** [comment]
Okay, turning on the signing for PRs worked. Now when I run the app I get this instead: 

Screenshot 2019-11-21 12 21 06

And clicking `open` works. No need to right-click etc.

I've enabled the master check, and I'll remove the env var from CircleCI, since that was the issue

**Comment by crstauf** [comment]
@karaggeorge @sindresorhus I just downloaded Kap today, and see this message when opening:

Screen Shot 2019-11-26 at 5 22 32 PM

Should I see [the image](https://user-images.githubusercontent.com/8822835/69361068-afd7ce80-0c59-11ea-8300-7613b2961b00.png) posted in [previous comment](https://github.com/wulkano/kap/pull/757#issuecomment-557188034)?

**Comment by karaggeorge** [comment]
@crstauf we haven't made an official release including this fix yet, so it won't be included in the packaged version you downloaded. If you want to test the current master, you can find it [here](http://kap-artifacts.now.sh/)

**Comment by crstauf** [comment]
Understood; thanks, George.

**Comment by crstauf** [comment]
@karaggeorge I've seen other issues that mention the latest release includes this, so confirming: the current release has this fixed, correct?
