### PR TITLE
Fix incorrect filename being displayed after export

### LINKED ISSUE #651: Incorrect filename displayed after export
**macOS version:**
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109

**Kap version:**
3.0.0 Beta5

#### Steps to reproduce

- Create a recording
- Edit the automatically generated filename to be "Demo.mp4"
- Export as MP4

#### Current behaviour
Following export, Kap shows the automatically generated filename as "successfully exported", not the edited name

#### Expected behaviour
In this case, Kap should show "Demo.mp4" as the exported filename, not the automatically generated name as a file of that name was not exported.

#### Workaround
Live with it.  ;-)

kap

### PR DESCRIPTION
**Pull request by blandonfrank**
When using the save to file service, the filename is placed in the context target path. Using that to display under export list - rather than using the generated default one.

Fixes #651

### CODE REVIEW

**Comment by sindresorhus** [comment]
You should use `path` methods instead of regex to modify the path.

**Comment by blandonfrank** [comment]
sindresorhus - you're right. I'm a total JS beginner. I went ahead and changed it to use `path` instead.

File: main/export.js [hunk 1]
```diff
@@ -38,7 +39,7 @@ class Export {
 
   get data() {
     return {
-      defaultFileName: this.defaultFileName,
+      defaultFileName: this.defaultFileName && (this.isDefault ? path.basename(this.context.targetFilePath) : this.defaultFileName),
```
Comment (karaggeorge) [inline main/export.js]:
```suggestion
      defaultFileName: this.isDefault ? path.basename(this.context.targetFilePath) : this.defaultFileName,
```

**Comment by sindresorhus** [comment]
Thank you, @blandonfrank :)
