### PR TITLE
Make sure plugins package.json exists before trying to access it

### LINKED ISSUE #558: Javascript error upon opening beta on 10.12.6 Sierra
Hi I get this error when I try to open the program

A JavaScript error occurred in the main process

Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/xxxxx/Library/Application Support/Kap Beta/plugins/package.json'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at getExportOptions (/Applications/Kap Beta.app/Contents/Resources/app.asar/main/export-options.js:35:18)
    at Object.<anonymous> (/Applications/Kap Beta.app/Contents/Resources/app.asar/main/export-options.js:90:12)
    at Object.<anonymous> (/Applications/Kap Beta.app/Contents/Resources/app.asar/main/export-options.js:97:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)

### PR DESCRIPTION
**Pull request by karaggeorge**
Fixes #558

### CODE REVIEW

File: main/export-options.js [hunk 1]
```diff
@@ -32,6 +33,13 @@ const prettifyFormat = format => {
...
 const getExportOptions = () => {
   const cwd = path.join(app.getPath('userData'), 'plugins');
+  const fp = path.join(cwd, 'package.json');
+
+  if (!fs.existsSync(fp)) {
+    makeDir.sync(cwd);
+    fs.writeFileSync(fp, '{"dependencies":{}}');
+  }
+
   const pkg = fs.readFileSync(path.join(cwd, 'package.json'), 'utf8');
```
Comment (albinekb) [inline main/export-options.js]: use `fp` here too

Comment (albinekb) [reply main/export-options.js]: I would also rename it to `packageJsonPath` to make it easier to read the code
